import { exec } from 'node:child_process'
import { readFile, writeFile } from 'node:fs/promises'
import { join, basename } from 'node:path'

// --- Configuration ---
/**
 * The base URL of your GitHub repository.
 * @example 'https://github.com/my-org/my-repo'
 */
const REPO_BASE_URL = 'https://github.com/Caesar2011/mcp-monorepo'

// --- ANSI Colors for Logging ---
const c = {
  reset: '\x1b[0m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  gray: '\x1b[90m',
}

// --- Type Definitions ---
interface PackageJson {
  name: string
  version: string
  description?: string
  author?: string | { name?: string }
  license?: string
  private?: boolean
  bin?: string | Record<string, string>
}

interface EnvVar {
  name: string
  description: string
  default: string
}

// --- Main Orchestration ---
/**
 * Main function to generate a README for a single package.
 * Assumes the script is executed with the package's root as the CWD.
 */
async function main(): Promise<void> {
  const packagePath = process.cwd()
  const pkgJsonPath = join(packagePath, 'package.json')

  let pkgJson: PackageJson
  try {
    pkgJson = JSON.parse(await readFile(pkgJsonPath, 'utf-8'))
  } catch (error) {
    console.error(`${c.red}Error: package.json not found in CWD (${packagePath}).${c.reset}`)
    console.error(error)
    process.exit(1)
  }

  if (pkgJson.private) {
    console.log(`${c.gray}Skipping private package: ${pkgJson.name}${c.reset}`)
    return
  }

  console.log(`Generating README for package: ${c.yellow}${pkgJson.name}${c.reset}`)

  const docgenPath = join(packagePath, '.docgen')

  // 1. Gather all data sources
  const [partialReadme, envVars, changelog] = await Promise.all([
    readFileIfExists(join(docgenPath, 'PARTIAL.md')),
    readJsonFile<EnvVar[]>(join(docgenPath, 'env.spec.json')),
    readFileIfExists(join(packagePath, 'CHANGELOG.md')),
  ])

  // 2. Assemble content sections
  const sections = [
    generateHeader(new Date()),
    generateTitleAndBadges(pkgJson, packagePath),
    partialReadme,
    generateEnvSection(envVars),
    generateChangelogSection(changelog),
    generateFooter(pkgJson),
  ]

  // 3. Write the final README file
  const readmePath = join(packagePath, 'README.md')
  const finalReadme = sections.filter((s): s is string => !!s).join('\n\n')
  await writeFile(readmePath, finalReadme)

  // 4. Stage the generated README file to git
  await stageFileToGit(readmePath)

  console.log(`${c.green}✓ README for ${pkgJson.name} successfully generated and staged.${c.reset}`)
  process.exit(0)
}

// --- Section Generators ---

function generateHeader(date: Date): string {
  return `<!--
  DO NOT EDIT THIS FILE DIRECTLY.
  IT IS AUTOMATICALLY GENERATED.
  Last generated: ${date.toISOString()}
-->`
}

function generateTitleAndBadges(pkgJson: PackageJson, packagePath: string): string {
  const packageDirName = basename(packagePath)
  const repoUrl = `${REPO_BASE_URL}/tree/main/packages/${packageDirName}`
  const badges = [
    `![version](https://img.shields.io/badge/version-${pkgJson.version}-blue)`,
    `![repo](https://img.shields.io/badge/monorepo-source-blue?logo=github&link=${encodeURIComponent(repoUrl)})`,
  ]
  return [`# ${pkgJson.name}`, badges.join(' '), pkgJson.description].filter(Boolean).join('\n\n')
}

function generateChangelogSection(changelog: string | undefined): string | undefined {
  const MAX_CHANGELOG_ENTRIES = 3

  if (!changelog || !changelog.trim()) {
    return undefined
  }
  const normalizedChangelog = changelog
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .replace(/^### .*\n/gm, '')

  const versionRegex = /^##\s+([\d.a-z-]+)\s*([\s\S]*?)(?=(^##\s+)|$)/gm
  const entries: string[] = []
  let match: RegExpMatchArray | null

  while ((match = versionRegex.exec(normalizedChangelog))) {
    if (entries.length >= MAX_CHANGELOG_ENTRIES) {
      break
    }
    const version = match[1]
    const content = (match[2] || '').trim()
    if (version && content) {
      entries.push(`### Version ${version}\n\n${content}`)
    }
  }
  if (entries.length === 0) {
    return undefined
  }
  return `## Recent Changes\n\n${entries.join('\n\n')}`
}

function generateEnvSection(envVars: EnvVar[] | undefined): string | undefined {
  if (!envVars || envVars.length === 0) return undefined
  const header = `| Variable | Description | Default |\n| :--- | :--- | :--- |`
  const rows = envVars.map((v) => `| \`${v.name}\` | ${v.description} | \`${v.default}\` |`)
  return `## Environment Variables\n\n${header}\n${rows.join('\n')}`
}

function generateFooter(pkgJson: PackageJson): string {
  const authorName = typeof pkgJson.author === 'object' ? pkgJson.author.name : pkgJson.author
  const licenseText = pkgJson.license
    ? `This project is licensed under the ${pkgJson.license} License. See the [LICENSE](./LICENSE) file for details.`
    : ''
  return `---
## Authors

- ${authorName || 'The MCP Monorepo Team'}

## License

${licenseText}`
}

// --- Helper & Utility Functions ---

async function readFileIfExists(filePath: string): Promise<string | undefined> {
  try {
    return await readFile(filePath, 'utf-8')
  } catch {
    return undefined
  }
}

async function readJsonFile<T>(filePath: string): Promise<T | undefined> {
  const content = await readFileIfExists(filePath)
  return content ? (JSON.parse(content) as T) : undefined
}

/**
 * Executes `git add` for the specified file path, with logging and error handling.
 */
async function stageFileToGit(filePath: string): Promise<void> {
  try {
    await new Promise<void>((resolve) => {
      // Use the absolute path for git to avoid ambiguity
      exec(`git add "${filePath}"`, (error, stdout, stderr) => {
        if (error) {
          // Soft fail: Warn instead of throwing an error, as git may not be available.
          console.warn(
            `${c.yellow}Warning: Could not stage ${basename(filePath)}. Is git installed and is this a git repository?${c.reset}`,
          )
          console.warn(`${c.gray}${stderr}${c.reset}`)
          resolve() // Resolve without error to allow the script to continue
          return
        }
        console.log(`${c.cyan}  -> Staged ${basename(filePath)} to git.${c.reset}`)
        resolve()
      })
    })
  } catch (gitError) {
    console.warn(
      `${c.yellow}Warning: An unexpected error occurred while staging ${basename(filePath)}.${c.reset}`,
      gitError,
    )
  }
}

// --- Script Entry Point ---
main().catch((err) => {
  console.error(`${c.red}An unexpected top-level error occurred:${c.reset}`, err)
  process.exit(1)
})
